simpleSite/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('logout-func/', views.logout_func, name="logout"),
    path('create-group/', views.create_group, name='create_group'),

]

simpleSite/simpleSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('welkom.urls')),
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

simpleSite/welkom/urls.py
from django.urls import path
from . import views


app_name = 'welkom'
urlpatterns = [
    path('', views.welkom, name='welkom'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

simpleSite/home/models.py
from django.db import models
from django.contrib.auth.models import Group

# Creating a database model for the friend groups
class FriendGroup(Group):
    def __str__(self):
        return self.name

simpleSite/welkom/models.py
from django.db import models

# Create your models here.

simpleSite/home/forms.py
from django import forms

# A form for uploading files
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

simpleSite/home/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import django.contrib.auth as auth
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .models import FriendGroup
from .forms import UploadFileForm


# Function for saving files; needs to be based elsewhere in the final version
def save(f):
    return f.ch


# The home screen of a user
@login_required
def home(request):
    name = request.user.username
    user = User.objects.get(username=name)

    return render(request, 'home/homehtml.html')


# Login out a user using the default logout function of django
@login_required
def logout_func(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('welkom:welkom'))


# The view for creating a new friend group
@login_required
def create_group(request):
    if request.method == 'POST':
        # getting the user that makes a new group
        user = User.objects.get(username=request.user.username)

        # Getting the name from the form and making a group with the corresponding name
        friend_group_name = request.POST.get('friend_group_name')
        friend_group = FriendGroup(name=friend_group_name)

        # Adding the current user to the group and saving the group
        friend_group.user_set.add(user)
        friend_group.save()

        # Redirecting to the users home page
        return HttpResponseRedirect("/home/")

    # Loading the create group view
    return render(request, 'home/create_group.html')


def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            save(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

simpleSite/welkom/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
import django.contrib.auth as auth

from django.contrib.auth.models import User

# The view corresponding to the welkompage of the site
def welkom(request):
    # Setting the template for the welkom page
    template = loader.get_template('welkom/welkomhtml.html')
    context = {

    }

    # Rendering the template of the welkom page
    return HttpResponse(template.render(context, request))


# A funtion to register new users
def register(request):
    # Only runs when te form is returnd
    if request.method == 'POST':
        # Getting the entered name, password and email
        name = request.POST['your_name']
        password = request.POST['password']
        email = request.POST['email']

        # Checks wheter this username is already used
        check_name_exsists = User.objects.filter(username=name)
        if check_name_exsists:
            # Sending error message for when name is used
            return render(request, 'welkom/register.html',
                          {'error_message': "This name is already used"})
        else:
            # Creates new user and redirects to the welkom page
            User.objects.create_user(username=name, email=email, password=password)
            return HttpResponseRedirect(reverse('welkom:welkom'))

    # rendering the register page
    return render(request, 'welkom/register.html')


def login(request):

    # Only runs when te form is returnd
    if request.method == 'POST':

        # Checks wheter browser accepts the cookie (it is set below)
        if request.session.test_cookie_worked():

            # Deleting the test cookie to clean up
            request.session.delete_test_cookie()

            # Getting the username and password from the POST method
            username = request.POST.get('your_name')
            password = request.POST.get('password')

            # Checks whether the name and password make a valid combination
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                # Login in user
                auth.login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect("/home/")

            else:
                # Show an error page when invalid combo
                return HttpResponseRedirect("/account/invalid/")

        # If de browser does not accept cookies
        else:
            return HttpResponse("Please enable cookies and try again.")

    # Set the test cookie. is only set when method != POST
    request.session.set_test_cookie()

    return render(request, 'welkom/login.html')

simpleSite/home/templates/base.html
<!doctype html>
<html>
<head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'welkom/style.css' %}">
<title>{% block title %}{% endblock %}</title>

</head>

<body>
<nav>
      <a href="{% url 'home:logout-func' %}">Log out</a>
      <a href="{% url 'home:home' %}">{% request.user.username %}</a>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>
</body>
</html>

simpleSite/templates/base.html
<!doctype html>
<html>
<head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<title>{% block title %}{% endblock %}</title>

</head>

<body>
<nav>
    {% if request.user.is_authenticated %}
      <a href="{% url 'home:logout' %}">Logout</a>

    {% else %}
      <a href="{% url 'welkom:register' %}">Register</a>
      <a href="{% url 'welkom:login' %}">Log In</a>

    {% endif %}

</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

<section id="groups">
{% block groups %}{% endblock %}
</section>

</body>
</html>

simpleSite/templates/home/create_group.html
{% extends 'base.html' %}

{% block content %}

<form action = "{%url 'welkom:login' %}" method = "POST">
    {% csrf_token %}
    <input id="friend_group_name" type="text" name="friend_group_name" placeholder="Group name">

    <input type="submit" value="OK">
</form>

{% endblock %}

simpleSite/templates/home/homehtml.html
<!doctype html>
<html>
<head>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<title>{% block title %}{% endblock %}</title>

</head>

<body>
<nav>
    {% if request.user.is_authenticated %}
      <a href="{% url 'home:logout' %}">Logout</a>

    {% else %}
      <a href="{% url 'welkom:register' %}">Register</a>
      <a href="{% url 'welkom:login' %}">Log In</a>

    {% endif %}

</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% block content %}{% endblock %}
</section>

<section id="groups">

    <h2 class="groups">Groups</h2>

<ul>
{% for group in request.user.groups.all %}

    <li> {{group.name}}</li>

    {% endfor %}

    </ul>

    <a href="{% url 'home:create_group' %}"> Add group</a>

</section>

<section>
    <p>Click on the "Choose File" button to upload a file:</p>

<form action="/action_page.php">
  <input type="file" id="myFile" name="filename">
  <input type="submit">
</form>
</section>


</body>
</html>

simpleSite/templates/welkom/login.html
{% extends 'base.html' %}

{% block title %}
    <h1>Welkom!</h1>
{% endblock %}

{% block content %}

<form action = "{%url 'welkom:login' %}" method = "POST">
    {% csrf_token %}
    <input id="your_name" type="text" name="your_name" placeholder="Username">
    <input id="password" type="text" name="password" placeholder="Password">

    <input type="submit" value="OK">
</form>

{% endblock %}

simpleSite/templates/welkom/register.html
{% extends 'base.html' %}

{% block title %}
    Welkom!
{% endblock %}


{% block content %}

<main id="main-holder">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action = "{%url 'welkom:register'%}" method = "POST">
    {% csrf_token %}
    <input id="your_name" type="text" name="your_name" placeholder="Username">
    <input id="password" type="text" name="password" placeholder="Password">
    <input id="email" type="text" name="email" placeholder="Email">

    <input type="submit" value="OK">
</form>
</main>
{% endblock %}

simpleSite/templates/welkom/welkomhtml.html
{% extends 'base.html' %}

{% block header %}
  <h1 id='welkom-h1'>{% block title %}Welkom!{% endblock %}</h1>
{% endblock %}

{% block content %}

{% endblock %}